logger:
  level: "debug"
  source: false
storage:
  type: "db"
  db:
    dsn: "host=localhost port=5432 user=postgres password=postgres dbname=otus sslmode=disable"
httpserver:
  host: "localhost"
  port: "8080"
grpcserver:
  host: "localhost"
  port: "8090"