logger:
  level: "debug"
  source: false
storage:
  type: "db"
  db:
    dsn: "host=localhost port=5432 user=postgres password=postgres dbname=otus sslmode=disable"
queue:
  type: "rmq"
  rmq:
    dsn : "amqp://guest:guest@localhost:5672"
    qname: "calendarmesssages"
cleaner:
  tickinterval: "30s"
  outdatetime: "8760h"
scanner:
  tickinterval: "10s"
  notificationinterval: "15m"